
all:
	sudo apt-get install build-essential python-dev python-setuptools python-numpy python-scipy libatlas-dev libatlas3-base
	sudo apt-get install liblapack3 liblapack-dev
	sudo apt-get install python-matplotlib
	sudo apt-get install python-pip
	sudo pip install scikit-learn
	sudo pip install cvxopt==1.1.8
